apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  # 服务器会话密钥（随机生成）
  server.secretkey: "Wc8a87diaeUo+eo2mYGCE/A78YybDZ9Id0vIxMDuCOM="
  
  # 空的 webhook secret
  webhook.github.secret: ""
  
  # 管理员密码（ArgoCD 会自动处理）
  # 不在这里设置，让 ArgoCD 自动生成
  
  # TLS 配置（可选）
  # tls.crt: |
  #   -----BEGIN CERTIFICATE-----
  #   ...
  #   -----END CERTIFICATE-----
  # tls.key: |
  #   -----BEGIN PRIVATE KEY-----
  #   ...
  #   -----END PRIVATE KEY-----