apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repository.credentials: |
    - url: https://github.com/your-org/
      passwordSecret:
        name: github-token
        key: token
      usernameSecret:
        name: github-token
        key: username