apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
  labels:
    app: argocd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-server
  template:
    metadata:
      labels:
        app: argocd-server
    spec:
      serviceAccountName: argocd-server
      containers:
      - name: argocd-server
        image: argoproj/argocd:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: https
        env:
        - name: ARGOCD_SERVER_REPOSITORY_TIMEOUT
          value: "300"
        - name: ARGOCD_REDIS_ADDRESS
          value: "argocd-redis:6379"
        # 添加启动命令
        command: ["argocd-server"]
        args:
        - "--insecure"
        - "--staticassets"
        - "/shared/app"
        - "--redis"
        - "argocd-redis:6379"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30  # 增加到30秒，给启动更多时间
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 60  # 增加到60秒
          periodSeconds: 30
        resources:
          requests:
            memory: "256Mi"  
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"